/**
 * `@boarteam/fix-dict-fix44` — the FIX 4.4 dictionary as data.
 *
 * The dictionary JSON and its typed `Tags` / `MsgType` / enum helpers are generated by
 * `@boarteam/fix-codegen` from the FIX 4.4 specification (M1). This placeholder keeps the
 * package buildable until generation lands.
 */

export const DICTIONARY_VERSION = 'FIX.4.4';
