import type { DictionaryJSON } from '@boarteam/fix';
import { sanitizeIdentifier } from './fields';

/** Serialise the dictionary as pretty-printed JSON (the shipped data file). */
export function emitDictionaryJson(dict: DictionaryJSON): string {
  return `${JSON.stringify(dict, null, 2)}\n`;
}

/**
 * Emit the `@boarteam/fix-dict-fix44` entry point: the typed dictionary export plus
 * `Tags` (field name → tag) and `MsgType` (message name → MsgType value) const maps.
 * Keys are quoted so non-identifier names stay valid; `MsgType` keys are sanitised to
 * identifiers and de-duplicated.
 */
export function emitIndexTs(dict: DictionaryJSON): string {
  const tags = Object.values(dict.fields)
    .slice()
    .sort((a, b) => a.tag - b.tag)
    .map((f) => `  ${JSON.stringify(f.name)}: ${f.tag},`)
    .join('\n');

  const used = new Map<string, number>();
  const msgTypes = dict.messages
    .slice()
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((m) => {
      let key = sanitizeIdentifier(m.name) || `Msg_${m.msgType}`;
      const seen = used.get(key);
      if (seen !== undefined) {
        used.set(key, seen + 1);
        key = `${key}_${seen + 1}`;
      } else {
        used.set(key, 0);
      }
      return `  ${JSON.stringify(key)}: ${JSON.stringify(m.msgType)},`;
    })
    .join('\n');

  return `/* GENERATED by @boarteam/fix-codegen from the FIX 4.4 Markdown reference. DO NOT EDIT BY HAND. */
import type { DictionaryJSON } from '@boarteam/fix';
import dictionaryJson from './dictionary.json';

/**
 * The complete FIX 4.4 dictionary as data. Pass to \`loadDictionary\` from \`@boarteam/fix\`
 * to get a runtime index, or to \`createFixEngine\`.
 */
export const dictionary = dictionaryJson as unknown as DictionaryJSON;

/** Dialect identifier (the \`BeginString\`, tag 8, value). */
export const DICTIONARY_VERSION = ${JSON.stringify(dict.version)} as const;

/** Field tags keyed by field name. */
export const Tags = {
${tags}
} as const;
export type TagName = keyof typeof Tags;

/** \`MsgType\` (tag 35) values keyed by message name. */
export const MsgType = {
${msgTypes}
} as const;
export type MsgTypeName = keyof typeof MsgType;
`;
}
