/* GENERATED by @boarteam/fix-codegen from the QuickFIX/J FIXT.1.1 XML data dictionary. DO NOT EDIT BY HAND. */
import { messageFactory, messageTypeGuard } from '@boarteam/fix';
import type { DictionaryJSON, MessageFactory, MessageView } from '@boarteam/fix';
import dictionaryJson from './dictionary.json';

/**
 * The complete FIXT.1.1 dictionary as data. Pass to `loadDictionary` from `@boarteam/fix`
 * to get a runtime index, or to `createFixEngine`.
 */
export const dictionary = dictionaryJson as unknown as DictionaryJSON;

/** Dialect identifier (the `BeginString`, tag 8, value). */
export const DICTIONARY_VERSION = "FIXT.1.1" as const;

/** Field tags keyed by field name. */
export const Tags = {
  "BeginSeqNo": 7,
  "BeginString": 8,
  "BodyLength": 9,
  "CheckSum": 10,
  "EndSeqNo": 16,
  "MsgSeqNum": 34,
  "MsgType": 35,
  "NewSeqNo": 36,
  "PossDupFlag": 43,
  "RefSeqNum": 45,
  "SenderCompID": 49,
  "SenderSubID": 50,
  "SendingTime": 52,
  "TargetCompID": 56,
  "TargetSubID": 57,
  "Text": 58,
  "Signature": 89,
  "SecureDataLen": 90,
  "SecureData": 91,
  "SignatureLength": 93,
  "RawDataLength": 95,
  "RawData": 96,
  "PossResend": 97,
  "EncryptMethod": 98,
  "HeartBtInt": 108,
  "TestReqID": 112,
  "OnBehalfOfCompID": 115,
  "OnBehalfOfSubID": 116,
  "OrigSendingTime": 122,
  "GapFillFlag": 123,
  "DeliverToCompID": 128,
  "DeliverToSubID": 129,
  "ResetSeqNumFlag": 141,
  "SenderLocationID": 142,
  "TargetLocationID": 143,
  "OnBehalfOfLocationID": 144,
  "DeliverToLocationID": 145,
  "XmlDataLen": 212,
  "XmlData": 213,
  "MessageEncoding": 347,
  "EncodedTextLen": 354,
  "EncodedText": 355,
  "LastMsgSeqNumProcessed": 369,
  "RefTagID": 371,
  "RefMsgType": 372,
  "SessionRejectReason": 373,
  "MaxMessageSize": 383,
  "NoMsgTypes": 384,
  "MsgDirection": 385,
  "TestMessageIndicator": 464,
  "Username": 553,
  "Password": 554,
  "NoHops": 627,
  "HopCompID": 628,
  "HopSendingTime": 629,
  "HopRefID": 630,
  "NextExpectedMsgSeqNum": 789,
  "NewPassword": 925,
  "ApplVerID": 1128,
  "CstmApplVerID": 1129,
  "RefApplVerID": 1130,
  "RefCstmApplVerID": 1131,
  "DefaultApplVerID": 1137,
  "ApplExtID": 1156,
  "EncryptedPasswordMethod": 1400,
  "EncryptedPasswordLen": 1401,
  "EncryptedPassword": 1402,
  "EncryptedNewPasswordLen": 1403,
  "EncryptedNewPassword": 1404,
  "RefApplExtID": 1406,
  "DefaultApplExtID": 1407,
  "DefaultCstmApplVerID": 1408,
  "SessionStatus": 1409,
  "DefaultVerIndicator": 1410,
} as const;
export type TagName = keyof typeof Tags;

/** `MsgType` (tag 35) values keyed by message name. */
export const MsgType = {
  "Heartbeat": "0",
  "Logon": "A",
  "Logout": "5",
  "Reject": "3",
  "ResendRequest": "2",
  "SequenceReset": "4",
  "TestRequest": "1",
} as const;
export type MsgTypeName = keyof typeof MsgType;

/**
 * Union of the on-the-wire `MsgType` values (`"A" | "0" | ...`) — the value-side
 * counterpart of `MsgTypeName` (which is the union of message *names*). Lets
 * consumers write `msgType: MsgType` in type positions.
 */
export type MsgType = (typeof MsgType)[keyof typeof MsgType];

/**
 * Field names keyed by tag number — the reverse of `Tags`. Useful for log lines
 * and session-level `Reject` construction without loading the full dictionary:
 * `TagNames[55] === 'Symbol'`. `undefined` for tags outside the dictionary.
 */
export const TagNames: { readonly [tag: number]: TagName | undefined } = {
  7: "BeginSeqNo",
  8: "BeginString",
  9: "BodyLength",
  10: "CheckSum",
  16: "EndSeqNo",
  34: "MsgSeqNum",
  35: "MsgType",
  36: "NewSeqNo",
  43: "PossDupFlag",
  45: "RefSeqNum",
  49: "SenderCompID",
  50: "SenderSubID",
  52: "SendingTime",
  56: "TargetCompID",
  57: "TargetSubID",
  58: "Text",
  89: "Signature",
  90: "SecureDataLen",
  91: "SecureData",
  93: "SignatureLength",
  95: "RawDataLength",
  96: "RawData",
  97: "PossResend",
  98: "EncryptMethod",
  108: "HeartBtInt",
  112: "TestReqID",
  115: "OnBehalfOfCompID",
  116: "OnBehalfOfSubID",
  122: "OrigSendingTime",
  123: "GapFillFlag",
  128: "DeliverToCompID",
  129: "DeliverToSubID",
  141: "ResetSeqNumFlag",
  142: "SenderLocationID",
  143: "TargetLocationID",
  144: "OnBehalfOfLocationID",
  145: "DeliverToLocationID",
  212: "XmlDataLen",
  213: "XmlData",
  347: "MessageEncoding",
  354: "EncodedTextLen",
  355: "EncodedText",
  369: "LastMsgSeqNumProcessed",
  371: "RefTagID",
  372: "RefMsgType",
  373: "SessionRejectReason",
  383: "MaxMessageSize",
  384: "NoMsgTypes",
  385: "MsgDirection",
  464: "TestMessageIndicator",
  553: "Username",
  554: "Password",
  627: "NoHops",
  628: "HopCompID",
  629: "HopSendingTime",
  630: "HopRefID",
  789: "NextExpectedMsgSeqNum",
  925: "NewPassword",
  1128: "ApplVerID",
  1129: "CstmApplVerID",
  1130: "RefApplVerID",
  1131: "RefCstmApplVerID",
  1137: "DefaultApplVerID",
  1156: "ApplExtID",
  1400: "EncryptedPasswordMethod",
  1401: "EncryptedPasswordLen",
  1402: "EncryptedPassword",
  1403: "EncryptedNewPasswordLen",
  1404: "EncryptedNewPassword",
  1406: "RefApplExtID",
  1407: "DefaultApplExtID",
  1408: "DefaultCstmApplVerID",
  1409: "SessionStatus",
  1410: "DefaultVerIndicator",
};

/**
 * Message names keyed by `MsgType` (tag 35) value — the reverse of `MsgType`.
 * `undefined` for values outside the dictionary.
 */
export const MsgTypeNames: { readonly [msgType: string]: MsgTypeName | undefined } = {
  "0": "Heartbeat",
  "A": "Logon",
  "5": "Logout",
  "3": "Reject",
  "2": "ResendRequest",
  "4": "SequenceReset",
  "1": "TestRequest",
};

/** `ApplVerID` (tag 1128) values keyed by spec value name. */
export const ApplVerID = {
  "FIX27": "0",
  "FIX30": "1",
  "FIX40": "2",
  "FIX41": "3",
  "FIX42": "4",
  "FIX43": "5",
  "FIX44": "6",
  "FIX50": "7",
  "FIX50SP1": "8",
  "FIX50SP2": "9",
  "FIXLatest": "10",
} as const;
export type ApplVerID = (typeof ApplVerID)[keyof typeof ApplVerID];

/** `EncryptMethod` (tag 98) values keyed by spec value name. */
export const EncryptMethod = {
  "NONE_OTHER": "0",
  "PKCS": "1",
  "DES": "2",
  "PKCS_DES": "3",
  "PGP_DES": "4",
  "PGP_DES_MD5": "5",
  "PEM_DES_MD5": "6",
} as const;
export type EncryptMethod = (typeof EncryptMethod)[keyof typeof EncryptMethod];

/** `GapFillFlag` (tag 123) values keyed by spec value name. */
export const GapFillFlag = {
  "SEQUENCE_RESET_IGNORE_MSG_SEQ_NUM": "N",
  "GAP_FILL_MESSAGE_MSG_SEQ_NUM_FIELD_VALID": "Y",
} as const;
export type GapFillFlag = (typeof GapFillFlag)[keyof typeof GapFillFlag];

/** `MsgDirection` (tag 385) values keyed by spec value name. */
export const MsgDirection = {
  "RECEIVE": "R",
  "SEND": "S",
} as const;
export type MsgDirection = (typeof MsgDirection)[keyof typeof MsgDirection];

/** `PossDupFlag` (tag 43) values keyed by spec value name. */
export const PossDupFlag = {
  "ORIGINAL_TRANSMISSION": "N",
  "POSSIBLE_DUPLICATE": "Y",
} as const;
export type PossDupFlag = (typeof PossDupFlag)[keyof typeof PossDupFlag];

/** `PossResend` (tag 97) values keyed by spec value name. */
export const PossResend = {
  "ORIGINAL_TRANSMISSION": "N",
  "POSSIBLE_RESEND": "Y",
} as const;
export type PossResend = (typeof PossResend)[keyof typeof PossResend];

/** `ResetSeqNumFlag` (tag 141) values keyed by spec value name. */
export const ResetSeqNumFlag = {
  "NO": "N",
  "YES_RESET_SEQUENCE_NUMBERS": "Y",
} as const;
export type ResetSeqNumFlag = (typeof ResetSeqNumFlag)[keyof typeof ResetSeqNumFlag];

/** `SessionRejectReason` (tag 373) values keyed by spec value name. */
export const SessionRejectReason = {
  "INVALID_TAG_NUMBER": "0",
  "REQUIRED_TAG_MISSING": "1",
  "TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE": "2",
  "UNDEFINED_TAG": "3",
  "TAG_SPECIFIED_WITHOUT_A_VALUE": "4",
  "VALUE_IS_INCORRECT": "5",
  "INCORRECT_DATA_FORMAT_FOR_VALUE": "6",
  "DECRYPTION_PROBLEM": "7",
  "SIGNATURE_PROBLEM": "8",
  "COMPID_PROBLEM": "9",
  "SENDINGTIME_ACCURACY_PROBLEM": "10",
  "INVALID_MSGTYPE": "11",
  "XML_VALIDATION_ERROR": "12",
  "TAG_APPEARS_MORE_THAN_ONCE": "13",
  "TAG_SPECIFIED_OUT_OF_REQUIRED_ORDER": "14",
  "REPEATING_GROUP_FIELDS_OUT_OF_ORDER": "15",
  "INCORRECT_NUMINGROUP_COUNT_FOR_REPEATING_GROUP": "16",
  "NON_DATA_VALUE_INCLUDES_FIELD_DELIMITER": "17",
  "INVALID_UNSUPPORTED_APPLICATION_VERSION": "18",
  "OTHER": "99",
} as const;
export type SessionRejectReason = (typeof SessionRejectReason)[keyof typeof SessionRejectReason];

/** `SessionStatus` (tag 1409) values keyed by spec value name. */
export const SessionStatus = {
  "SESSION_ACTIVE": "0",
  "SESSION_PASSWORD_CHANGED": "1",
  "SESSION_PASSWORD_DUE_TO_EXPIRE": "2",
  "NEW_SESSION_PASSWORD_DOES_NOT_COMPLY_WITH_POLICY": "3",
  "SESSION_LOGOUT_COMPLETE": "4",
  "INVALID_USERNAME_OR_PASSWORD": "5",
  "ACCOUNT_LOCKED": "6",
  "LOGONS_ARE_NOT_ALLOWED_AT_THIS_TIME": "7",
  "PASSWORD_EXPIRED": "8",
} as const;
export type SessionStatus = (typeof SessionStatus)[keyof typeof SessionStatus];

/** `TestMessageIndicator` (tag 464) values keyed by spec value name. */
export const TestMessageIndicator = {
  "FALES": "N",
  "TRUE": "Y",
} as const;
export type TestMessageIndicator = (typeof TestMessageIndicator)[keyof typeof TestMessageIndicator];

/**
 * Enumerated field values: field name → spec value name → on-the-wire string.
 * `Enums.MDEntryType.BID === "0"`. Values are wire-verbatim strings even for
 * int-typed fields (`Enums.SessionRejectReason.INVALID_TAG_NUMBER === "0"`),
 * so they compare directly against tokenizer and parser output. Fields are
 * sorted by name; values keep the spec's order. Names that start with a digit
 * (`"401K"`) need bracket access. Each entry references the top-level const
 * of the same name (`Enums.MDEntryType === MDEntryType`).
 * Exceptions with no top-level const, inlined here: `MsgType` — see the note on each entry.
 */
export const Enums = {
  "ApplVerID": ApplVerID,
  "EncryptMethod": EncryptMethod,
  "GapFillFlag": GapFillFlag,
  "MsgDirection": MsgDirection,
  // inlined — top-level export skipped: the field name collides with another export of this package
  "MsgType": {
    "HEARTBEAT": "0",
    "TEST_REQUEST": "1",
    "RESEND_REQUEST": "2",
    "REJECT": "3",
    "SEQUENCE_RESET": "4",
    "LOGOUT": "5",
    "INDICATION_OF_INTEREST": "6",
    "ADVERTISEMENT": "7",
    "EXECUTION_REPORT": "8",
    "ORDER_CANCEL_REJECT": "9",
    "LOGON": "A",
    "NEWS": "B",
    "EMAIL": "C",
    "ORDER_SINGLE": "D",
    "ORDER_LIST": "E",
    "ORDER_CANCEL_REQUEST": "F",
    "ORDER_CANCEL_REPLACE_REQUEST": "G",
    "ORDER_STATUS_REQUEST": "H",
    "ALLOCATION_INSTRUCTION": "J",
    "LIST_CANCEL_REQUEST": "K",
    "LIST_EXECUTE": "L",
    "LIST_STATUS_REQUEST": "M",
    "LIST_STATUS": "N",
    "ALLOCATION_INSTRUCTION_ACK": "P",
    "DONT_KNOW_TRADE": "Q",
    "QUOTE_REQUEST": "R",
    "QUOTE": "S",
    "SETTLEMENT_INSTRUCTIONS": "T",
    "MARKET_DATA_REQUEST": "V",
    "MARKET_DATA_SNAPSHOT_FULL_REFRESH": "W",
    "MARKET_DATA_INCREMENTAL_REFRESH": "X",
    "MARKET_DATA_REQUEST_REJECT": "Y",
    "QUOTE_CANCEL": "Z",
    "QUOTE_STATUS_REQUEST": "a",
    "MASS_QUOTE_ACKNOWLEDGEMENT": "b",
    "SECURITY_DEFINITION_REQUEST": "c",
    "SECURITY_DEFINITION": "d",
    "SECURITY_STATUS_REQUEST": "e",
    "SECURITY_STATUS": "f",
    "TRADING_SESSION_STATUS_REQUEST": "g",
    "TRADING_SESSION_STATUS": "h",
    "MASS_QUOTE": "i",
    "BUSINESS_MESSAGE_REJECT": "j",
    "BID_REQUEST": "k",
    "BID_RESPONSE": "l",
    "LIST_STRIKE_PRICE": "m",
    "XML_MESSAGE": "n",
    "REGISTRATION_INSTRUCTIONS": "o",
    "REGISTRATION_INSTRUCTIONS_RESPONSE": "p",
    "ORDER_MASS_CANCEL_REQUEST": "q",
    "ORDER_MASS_CANCEL_REPORT": "r",
    "NEW_ORDER_CROSS": "s",
    "CROSS_ORDER_CANCEL_REPLACE_REQUEST": "t",
    "CROSS_ORDER_CANCEL_REQUEST": "u",
    "SECURITY_TYPE_REQUEST": "v",
    "SECURITY_TYPES": "w",
    "SECURITY_LIST_REQUEST": "x",
    "SECURITY_LIST": "y",
    "DERIVATIVE_SECURITY_LIST_REQUEST": "z",
    "DERIVATIVE_SECURITY_LIST": "AA",
    "NEW_ORDER_MULTILEG": "AB",
    "MULTILEG_ORDER_CANCEL_REPLACE": "AC",
    "TRADE_CAPTURE_REPORT_REQUEST": "AD",
    "TRADE_CAPTURE_REPORT": "AE",
    "ORDER_MASS_STATUS_REQUEST": "AF",
    "QUOTE_REQUEST_REJECT": "AG",
    "RFQ_REQUEST": "AH",
    "QUOTE_STATUS_REPORT": "AI",
    "QUOTE_RESPONSE": "AJ",
    "CONFIRMATION": "AK",
    "POSITION_MAINTENANCE_REQUEST": "AL",
    "POSITION_MAINTENANCE_REPORT": "AM",
    "REQUEST_FOR_POSITIONS": "AN",
    "REQUEST_FOR_POSITIONS_ACK": "AO",
    "POSITION_REPORT": "AP",
    "TRADE_CAPTURE_REPORT_REQUEST_ACK": "AQ",
    "TRADE_CAPTURE_REPORT_ACK": "AR",
    "ALLOCATION_REPORT": "AS",
    "ALLOCATION_REPORT_ACK": "AT",
    "CONFIRMATION_ACK": "AU",
    "SETTLEMENT_INSTRUCTION_REQUEST": "AV",
    "ASSIGNMENT_REPORT": "AW",
    "COLLATERAL_REQUEST": "AX",
    "COLLATERAL_ASSIGNMENT": "AY",
    "COLLATERAL_RESPONSE": "AZ",
    "ORDER_MASS_ACTION_REQUEST": "CA",
    "USER_NOTIFICATION": "CB",
    "STREAM_ASSIGNMENT_REQUEST": "CC",
    "STREAM_ASSIGNMENT_REPORT": "CD",
    "STREAM_ASSIGNMENT_REPORT_ACK": "CE",
    "COLLATERAL_REPORT": "BA",
    "COLLATERAL_INQUIRY": "BB",
    "NETWORK_STATUS_REQUEST": "BC",
    "NETWORK_STATUS_RESPONSE": "BD",
    "USER_REQUEST": "BE",
    "USER_RESPONSE": "BF",
    "COLLATERAL_INQUIRY_ACK": "BG",
    "CONFIRMATION_REQUEST": "BH",
    "TRADING_SESSION_LIST_REQUEST": "BI",
    "TRADING_SESSION_LIST": "BJ",
    "SECURITY_LIST_UPDATE_REPORT": "BK",
    "ADJUSTED_POSITION_REPORT": "BL",
    "ALLOCATION_INSTRUCTION_ALERT": "BM",
    "EXECUTION_ACKNOWLEDGEMENT": "BN",
    "CONTRARY_INTENTION_REPORT": "BO",
    "SECURITY_DEFINITION_UPDATE_REPORT": "BP",
    "SETTLEMENT_OBLIGATION_REPORT": "BQ",
    "DERIVATIVE_SECURITY_LIST_UPDATE_REPORT": "BR",
    "TRADING_SESSION_LIST_UPDATER_EPORT": "BS",
    "MARKET_DEFINITION_REQUEST": "BT",
    "MARKET_DEFINITION": "BU",
    "MARKET_DEFINITION_UPDATE_REPORT": "BV",
    "APPLICATION_MESSAGE_REQUEST": "BW",
    "APPLICATION_MESSAGE_REQUEST_ACK": "BX",
    "APPLICATION_MESSAGE_REPORT": "BY",
    "ORDER_MASS_ACTION_REPORT": "BZ",
  },
  "PossDupFlag": PossDupFlag,
  "PossResend": PossResend,
  "ResetSeqNumFlag": ResetSeqNumFlag,
  "SessionRejectReason": SessionRejectReason,
  "SessionStatus": SessionStatus,
  "TestMessageIndicator": TestMessageIndicator,
} as const;
export type EnumFieldName = keyof typeof Enums;


// --- Typed message API (bodies, group entries, registry, factory, guard) ------------------
//
// Generated encode-side counterpart of `Tags`/`MsgType`/`Enums`. `<Comp>Fields` and
// `<Container>_<Counter>Entry` are augmentable interfaces (extend them via declaration merging
// to layer venue-specific tags onto an existing message without regenerating the dictionary);
// `<Msg>Body` types compose them; `MessageBodies` maps each `MsgType` value to its body;
// `isMessageType`/`MessageOf` are the read-side narrowing guard and its annotation alias.

/** `HopGrp` component fields. */
export interface HopGrpFields {
  NoHops?: HopGrp_NoHopsEntry[];
}

/** `MsgTypeGrp` component fields. */
export interface MsgTypeGrpFields {
  NoMsgTypes?: MsgTypeGrp_NoMsgTypesEntry[];
}

/** One `NoHops` (627) repeating-group entry. */
export interface HopGrp_NoHopsEntry {
  HopCompID?: string;
  HopSendingTime?: string;
  HopRefID?: number | string;
}

/** One `NoMsgTypes` (384) repeating-group entry. */
export interface MsgTypeGrp_NoMsgTypesEntry {
  RefMsgType?: string;
  MsgDirection?: MsgDirection;
  RefApplVerID?: string;
  RefApplExtID?: number | string;
  RefCstmApplVerID?: string;
  DefaultVerIndicator?: boolean;
}

/** `Heartbeat` (`0`) message body — settable fields/groups, excluding the header/trailer envelope. */
export type HeartbeatBody = {
  TestReqID?: string;
};

/** `TestRequest` (`1`) message body — settable fields/groups, excluding the header/trailer envelope. */
export type TestRequestBody = {
  TestReqID: string;
};

/** `ResendRequest` (`2`) message body — settable fields/groups, excluding the header/trailer envelope. */
export type ResendRequestBody = {
  BeginSeqNo: number | string;
  EndSeqNo: number | string;
};

/** `Reject` (`3`) message body — settable fields/groups, excluding the header/trailer envelope. */
export type RejectBody = {
  RefSeqNum: number | string;
  RefTagID?: number | string;
  RefMsgType?: string;
  RefApplVerID?: string;
  RefApplExtID?: number | string;
  RefCstmApplVerID?: string;
  SessionRejectReason?: SessionRejectReason | number;
  Text?: string;
  EncodedTextLen?: number | string;
  EncodedText?: string;
};

/** `SequenceReset` (`4`) message body — settable fields/groups, excluding the header/trailer envelope. */
export type SequenceResetBody = {
  GapFillFlag?: boolean;
  NewSeqNo: number | string;
};

/** `Logout` (`5`) message body — settable fields/groups, excluding the header/trailer envelope. */
export type LogoutBody = {
  SessionStatus?: SessionStatus | number;
  Text?: string;
  EncodedTextLen?: number | string;
  EncodedText?: string;
};

/** `Logon` (`A`) message body — settable fields/groups, excluding the header/trailer envelope. */
export type LogonBody = {
  EncryptMethod: EncryptMethod | number;
  HeartBtInt: number | string;
  RawDataLength?: number | string;
  RawData?: string;
  ResetSeqNumFlag?: boolean;
  NextExpectedMsgSeqNum?: number | string;
  MaxMessageSize?: number | string;
  TestMessageIndicator?: boolean;
  Username?: string;
  Password?: string;
  NewPassword?: string;
  EncryptedPasswordMethod?: number | string;
  EncryptedPasswordLen?: number | string;
  EncryptedPassword?: string;
  EncryptedNewPasswordLen?: number | string;
  EncryptedNewPassword?: string;
  SessionStatus?: SessionStatus | number;
  DefaultApplVerID: string;
  DefaultApplExtID?: number | string;
  DefaultCstmApplVerID?: string;
  Text?: string;
  EncodedTextLen?: number | string;
  EncodedText?: string;
} & Partial<MsgTypeGrpFields>;

/**
 * Every message body keyed by its `MsgType` (tag 35) wire value — the type registry that
 * makes `message(msgType)` / `engine.create(msgType)` return a builder typed to exactly
 * that message. First-definition-wins on a duplicate `MsgType`, matching the runtime
 * `Dictionary.messageByMsgType`. Extend it with new messages via declaration merging.
 */
export interface MessageBodies {
  "0": HeartbeatBody;
  "1": TestRequestBody;
  "2": ResendRequestBody;
  "3": RejectBody;
  "4": SequenceResetBody;
  "5": LogoutBody;
  "A": LogonBody;
}

/**
 * A typed, self-rendering message factory bound to this dictionary. Call it with a `MsgType`
 * value (e.g. `MsgType.MarketDataSnapshotFullRefresh`, the literal `"W"`) to build a
 * strongly-typed `MutableMessage`; use `message.immutable(...)` for the copy-on-write
 * variant. Supply the envelope (session/header fields) to `.render(envelope)`.
 *
 * ```ts
 * const wire = message('W')
 *   .set('MDReqID', 'req-1')
 *   .set('NoMDEntries', [{ MDEntryType: '0', MDEntryPx: '1.2345' }])
 *   .render({ SenderCompID: 'ME', TargetCompID: 'YOU', MsgSeqNum: 1, SendingTime: '20260716-12:00:00' });
 * ```
 */
export const message: MessageFactory<MessageBodies> = messageFactory<MessageBodies>(dictionary);

/**
 * A typed message-narrowing guard bound to this dictionary's `MessageBodies` — the read-side
 * counterpart of `message`. Given a message of unknown body (a `MessageView<any>`, e.g. at a
 * generic `send(message)` boundary where the concrete `MsgType` is erased) and a `MsgType`
 * value, it narrows the message so its `get()`/`has()` reads are typed to that message's body —
 * no `any`, no casts. Runtime is a plain `msgType` compare; the narrowing comes entirely from
 * `MessageBodies[M]`. It narrows to the read surface `MessageView` (shared by the mutable and
 * immutable message), not the mutable/immutable kind.
 *
 * ```ts
 * if (isMessageType(msg, 'W')) {
 *   // msg: MessageView<MarketDataSnapshotFullRefreshBody>
 *   const px = msg.get('NoMDEntries')?.[0]?.MDEntryPx;
 * }
 * ```
 */
export const isMessageType = messageTypeGuard<MessageBodies>();

/**
 * The read surface (`MessageView`) of the message whose `MsgType` value is `M` — a
 * convenience alias for annotating a narrowed message. `MessageOf<'W'>` is
 * `MessageView<MarketDataSnapshotFullRefreshBody>`.
 */
export type MessageOf<M extends keyof MessageBodies & string> = MessageView<MessageBodies[M] & object>;
